export const GET_ERROR="GET_ERROR";
export const GET_CATEGORIES="GET_CATEGORIES";
export const GET_CATEGORY="GET_CATEGORY";
export const DELETE_CATEGORY="DELETE_CATEGORY";
export const GET_ERRORS = "GET_ERRORS";